### PR TITLE
MERGE USER CMD:

### LINKED ISSUE #7: Command: USER
Parameters: \<user\> \<mode\> \<unused\> \<realname\>

Used at the beginning of connection to specify the username, hostname and realname of a new user.

The <mode> parameter should be a numeric, and can be used to automatically set user modes when registering with the server.  This parameter is a bitmask, with only 2 bits having any signification: if the bit 2 is set, the user mode 'w' will be set and if the bit 3 is set, the user mode 'i' will be set.

The \<realname\> may contain space characters.

Examples:

USER guest 0 * :Ronnie Reagan   _; User registering themselves with a  username of "guest" and real name "Ronnie Reagan"._

USER guest 8 * :Ronnie Reagan   _; User registering themselves with a username of "guest" and real name "Ronnie Reagan", and asking to be set invisible._

ERROR replies:

- **ERR_NEEDMOREPARAMS** - 461
"\<command\> :Not enough parameters"
         -> Returned by the server by numerous commands to indicate to the client that it didn't supply enough parameters.

- **ERR_ALREADYREGISTRED** - 462
":Unauthorized command (already registered)"
         -> Returned by the server to any link which tries to change part of the registered details (such as password or user details from second USER message).

### LINKED ISSUE #23: FIX: is nick available ?
There is an issue in the function to check if a nick is available.
The function should also check for all the channel names as a user cannot have a name that is already taken by a channel.

### PR DESCRIPTION
**Pull request by AdrianWeaver**
Adding User class : this class is mandatory for the registration process.

Fixing Nick class now behaving as expected for multiple users with the same nickname.

First time getting a message on irssi, yey \o/

Reworked the main to take password into account (Pass cmd still not done).

Updated the broadcast system for server/channel/clients.

Fixed tokeniser on ACommand.

There is still some work to be done on the registration process to confirm that the user is registered.
This will definitely need some additional work probably when the focus will be on the Pass cmd.

Close #7 
Close #23 

Co-authored-by: aweaver [aweaver@student.42.fr](mailto:aweaver@student.42.fr)
Co-authored-by: elouisia [elouisiade@live.fr](mailto:elouisiade@live.fr)

### CODE REVIEW

**Comment by AdrianWeaver** [comment]
Removed (squashed) the WIP commits.
This is nasty and the resulting commit might even be dirtier than keeping the WIP...
However this was done in a complex context with NOC and 42...

**Comment by AdrianWeaver** [comment]
Added a commit while we're at it to close #23

**Comment by AdrianWeaver** [comment]
Some errors that I thought were dealt with are not.
Closing the PR until a fix is found and added.

**Comment by AdrianWeaver** [comment]
Fixed the incorrect error messages.
Properly using the RPL message method in error() method.

Therefore reopening this PR!

**Review by Elena-Lou — APPROVED** [review]
Thank you again for a very productive day

**Pull request merged**
